# -*- coding: utf-8 -*-
"""Langchain -Chroma-Shubh .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u6uI2mkN50bQx9A2AwwyPnjCvBTdfIM2
"""

pip install -U langchain-core langchain-community langchain-openai langchain-chroma chromadb tiktoken

import os

os.environ["OPENAI_API_KEY"] = "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"
os.environ["OPENAI_API_BASE"] = "https://openrouter.ai/api/v1"

from langchain_openai import OpenAIEmbeddings
from langchain_chroma import Chroma
from langchain_core.documents import Document

from langchain_core.documents import Document

# Create LangChain documents for IPL players

doc1 = Document(
        page_content="Virat Kohli is one of the most successful and consistent batsmen in IPL history. Known for his aggressive batting style and fitness, he has led the Royal Challengers Bangalore in multiple seasons.",
        metadata={"team": "Royal Challengers Bangalore"}
    )
doc2 = Document(
        page_content="Rohit Sharma is the most successful captain in IPL history, leading Mumbai Indians to five titles. He's known for his calm demeanor and ability to play big innings under pressure.",
        metadata={"team": "Mumbai Indians"}
    )
doc3 = Document(
        page_content="MS Dhoni, famously known as Captain Cool, has led Chennai Super Kings to multiple IPL titles. His finishing skills, wicketkeeping, and leadership are legendary.",
        metadata={"team": "Chennai Super Kings"}
    )
doc4 = Document(
        page_content="Jasprit Bumrah is considered one of the best fast bowlers in T20 cricket. Playing for Mumbai Indians, he is known for his yorkers and death-over expertise.",
        metadata={"team": "Mumbai Indians"}
    )
doc5 = Document(
        page_content="Ravindra Jadeja is a dynamic all-rounder who contributes with both bat and ball. Representing Chennai Super Kings, his quick fielding and match-winning performances make him a key player.",
        metadata={"team": "Chennai Super Kings"}
    )

docs = [doc1, doc2, doc3, doc4, doc5]

vector_store = Chroma(
    embedding_function=OpenAIEmbeddings(),
    persist_directory='my_chroma_db',
    collection_name='sample'
)

vector_store.add_documents(docs)

vector_store.get(include=["documents", "metadatas","embeddings"])

vector_store.similarity_search(
    query="Who among these are a bowler?",
    k=2
)

vector_store.similarity_search_with_score(
    query="Who among these are a bowler?",
    k=2
)

vector_store.similarity_search_with_score(
    query="",
    filter={"team": "Chennai Super Kings"}
)

updated_doc1 = Document(
    page_content="Virat Kohli, the former captain of Royal Challengers Bangalore (RCB), is renowned for his aggressive leadership and consistent batting performances. He holds the record for the most runs in IPL history.",
    metadata={"team": "Royal Challengers Bangalore"}
)

vector_store.update_document(document_id='23814dad-bfab-4a71-8318-3312088eedf7', document=updated_doc1)

# view documents
vector_store.get(include=['embeddings','documents', 'metadatas'])

vector_store.delete(ids=['23814dad-bfab-4a71-8318-3312088eedf7'])

# view documents
vector_store.get(include=['embeddings','documents', 'metadatas'])

